namespace eval logo_utils {
    proc create_git_logo {} {
            image create photo gitlogo -data {
            iVBORw0KGgoAAAANSUhEUgAAAgAAAAI
            ACAMAAADDpiTIAAAAA3NCSVQICAjb4U
            /gAAAACXBIWXMAABApAAAQKQH1eOIPA
            AAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5r
            c2NhcGUub3Jnm+48GgAAAwBQTFRF///
            /AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAACy
            O34QAAAP90Uk5TAAECAwQFBgcICQoLD
            A0ODxAREhMUFRYXGBkaGxwdHh8gISIj
            JCUmJygpKissLS4vMDEyMzQ1Njc4OTo
            7PD0+P0BBQkNERUZHSElKS0xNTk9QUV
            JTVFVWV1hZWltcXV5fYGFiY2RlZmdoa
            WprbG1ub3BxcnN0dXZ3eHl6e3x9fn+A
            gYKDhIWGh4iJiouMjY6PkJGSk5SVlpe
            YmZqbnJ2en6ChoqOkpaanqKmqq6ytrq
            +wsbKztLW2t7i5uru8vb6/wMHCw8TFx
            sfIycrLzM3Oz9DR0tPU1dbX2Nna29zd
            3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T
            19vf4+fr7/P3+6wjZNQAAHSdJREFUGB
            ntwQmAjeX+B/DvmX0Y+y6uJcWkst3rR
            qVCJColOSnRLkskxLWUErlFruUvtLi2
            CrnKUpIWomyVLEkkstwZhmEss5w53/+
            V69rmnDnv+z6/933PmefzATRN0zRN0z
            RN0yJXieSGTVrc1aFz194Dh40aN2X63
            IXLli2cO33KuFHDBvbu2qXDXS2aNEwu
            AS2iJFS9rm3XYZM/XLM7iyHJ2r3mw8n
            Dura9rmoCtPBVpGGXUe9+sS2dFqRv++
            LdUV0aFoEWTkrd+MTYT3+nQr9/OvaJG
            0tBc7uKzXtO+jKVQlK/nNSzeUVorpTU
            bOjSI7TBkaVDmyVBc5NKHcZt8NFGvg3
            jOlSC5gJRdbvP3k1H7J7dvU4UNOckNh
            u69BgddWzp0GaJ0BxQ9pEFJ+gKJxY8U
            haarZKfW51LF8ld/VwyNHtE3zT6F7rQ
            L6NvioYmrEj7GWl0rbQZ7YtAE1Om2yd
            ZdLmsT7qVgSYg5q5/ZTMsZP/rrhhoal
            0zJoVhJGXMNdCUKdljPcPO+h4loSkQf
            fucTIalzDm3R0OzptYr+xnG9r9SC5pp
            8Y9+w7D3zaPx0MwoPvAAI8KBgcWhGVV
            5dAYjRsboytCMuGZ6NiNK9vRroIXqli
            WMQEtugRaC6PbrGKHWtY+GFlxitx2MY
            Du6JUILrMiQVEa41CFFoOUttkcKC4CU
            HrHQLuXx7mABscPrgXaRZutZgKxvBu1
            89ZaygFlaD9pZ1Wb5WeD4Z1WDdlrpsV
            kskLLGloZWePBRFlhHBxdGweZ5/AALt
            AOPe1CAXb2KBd6qq1FQJY7IpsbsEYko
            kFrspPaHnS1Q8JSdRe1/ZpVFweJ57DC
            18xx+zIMCJHkFtYusSEZBkfBSFrVLZL
            2UgAKh2XZqedreDJGv+D+pBfTP4ohwN
            +6mFsTuGxHJYl70UQvK92IMIlb1b6jl
            65vqiFAPHqMWgmMPIhIVnUUtRLOKIuI
            03kUtZLsaI7JED/VRM8A3NBoRpMrX1A
            z6ugoihjedmmHpXkSGuKnUTJkahwhQb
            hU1k74ui7BXfw810/bUQ5jrcJKaBSfa
            I5x5hlOzxv+iB2GryIfULJtfGGGq+mZ
            qCmysirDU9BA1JQ42QRjqnkNNkewnEG
            5ip1BTaEIMwkrpFdSUWl4CYaTST9QU2
            1QeYaPGb9SU21EVYeLaf1MTsDcZYeG6
            w9REHGyAMND8ODUhR5vA9dpmUhNz8na
            43EM+aoKyO8DVevipicp9HC42mJq4fn
            Ct16jZ4GW4U9RUaraY4IELed6hZpM34
            EKvU7PNKLjO89RsNBAu04uarZ6Cq3T2
            U7OV/wG4yN0+ajbLuQOu0TyTmu1O3QK
            XuO44NQdkNIQrXHOYmiPSroYLXH6Amk
            P2V4fjLttFzTG/VoTDSm2h5qAtpeCo+
            NXUHLU6Hk56h5rD3oGD+lBzXB84pqWP
            muN8LeGQK49Qc4EjV8IRxbdRc4VtxeG
            A6E+oucQn0bDfaGquMRq260LNRbrAZo
            0yqblIZiPYqtIBaq5yoBJslLiBmstsS
            IR93qPmOu/BNt2ouVA32KT2SWoudLI2
            bBG/kZorbYyHHcZSc6mxsEErPzWX8re
            CuLIpVCXlq8nP9hs5Zd7nGw+x4Dn6+b
            TxIwb27NJ1wpdpVCWlLKQtoSL3F8c5V
            3SZutXPgiJr3cTOyR6cU/GfVGQJhD1N
            RX7z4CIl24z4jpFv95gb4nGxhlTlaYi
            6NpOKvIK81Hx+GyPZjlF/QZ62U5HMay
            EoYTNVqYsA6o3azcj08/C6COQFqrI5A
            XImUpWfEJjn+vFpjDS+D25GEFdQmYkQ
            cweVeR5BJT7yPSPJwRGVEdwaKnMHhJQ
            /SGVqIj/Xv5fNCLGhSwLy8zSVOVgeMj
            6mMt8hBBWHHWD4y57dGCEo56MyH0NER
            6rTHyGJ6/gNw9uBFyogNJ9QnY4QUCKF
            6lRBqBpMy2TYWt0xFqHqTHVSSkC9qVR
            nGwwoPXAPw1HmtAYwoJyf6kyFcjf6qc
            4EGBJ9zwqGm9zpVWDMD1THfyMUi9tCh
            drCqObfMqx8XAdGvUqFtsRBrcFUyFcM
            xrX5nmFjfVMYdytVGgylrjhFhb6FGZ7
            2WxkWdnTwwISEU1To1BVQ6TOqNBzmRH
            XaSddL7RkLc5ZSpc+gUCcqdTPMinliD
            13t+ItFYFZfKtUJypQ6SJVOxMG8+F5H
            qEzuiUOHTuRSmZw3ysO8a6nUwVJQ5W0
            q9SksKT+HpmTv+Xb+xMG9n3yo/R3Nr6
            +fXK18sTj8Ia5Y+WrJ9a9vfkf7h57sP
            Xji/G/3ZNOUj2rCkhQq9TYUuYlqvQKL
            2uxhyHL2rl0wacijreqU9SBknrJ1Wj0
            6ZNKCtXtzGLJ97WDREqp1E5SI30a1Ho
            BVSf/IZb7SV015ulnFKFgSVbHZ01NWp
            TNf/v8rBqtGUq1t8VDheSp2DaxruJGB
            Zax5u0/LSlCoUss+b6/JYGCbG8M6LxV
            7HgpUPEG1suOgQMyAk7xU7sbp/VtX9U
            CEp2rr/tM35vJSpwbHQoFkKnaiAqybQ
            sU2QY3LP+MFcta82qY4xBVv8+qaHF7g
            8yuhRPQpKjYZliX7qNhsqNL5EP8ra+X
            LLZJgm6QWL6/M4n+lPQxV1lExXy1YtY
            CqDYQyZWaSPLF86M0JsF3CzUOXnyA5q
            wyUeZOqzYdF11O51lCo5YDGsXBMbOMB
            LaFQTyrXCNasonLVoAXQlMqtgCVtqV4
            haAEkU702sCD6Jyp3HFogJane5iiY9w
            TV2wUtEE8O1XsYphXaT/XWQgtoP9X7P
            QFmDaKARdAC+oEC+sGk0kcp4B1oAS2l
            gMMlYM4/KOHv0AKaQQl/hynVsyihL7S
            ARlPCqcowYxZFPAUtoGEU8RZMqOajiJ
            7QAhpOEdmVYNx4yngGWkAjKONVGFbqB
            GX0gxbQKMo4WgxGDaWQAdACeo1C+sOg
            xFQKGQwtoNcpZF8cjOlKKS9AC2gcpXS
            BIVG/UMpwaAFNpJTNHhjRjmJegxbQVI
            ppDSO+pZj3oAW0hGK+hAE3Us430ALaR
            Dl/Qeg+opwD0AI6SjlzELJkP+X446EF
            UJSCfJcjVG9R0hXQAriakiYiRBWyKOl
            WaAG0oqSTpRGakRT1GLQAnqCo5xGS2F
            SKehlaACMoam80QtGWspZBC2AZZd2GU
            HxEWceioeUp+hhlzUEIyuVQWF1oeapL
            YZklkb++lNYNWp66UVoP5G8Lpc2Elqe
            ZlLYB+WpIcbug5WkXxV2L/EyivArQ8l
            CB8l5HPhLSKa8DtDx0oLyDsQiuI20wB
            1oe5tAG9yC4ZbTBySRol0g6SRssRFB/
            yqUdHoB2iQdoh5zyCGYIbbEI2iUW0Rb
            9EIRnJ22RXRLaRUpm0xZbEcRNtMnj0C
            7yOG3yVwT2Fm2yHNpFltMmExFQVCpt8
            iW0i3xJm+xFQI1pkx2loF2k9E7apAEC
            GUl7HK4J7RK1jtAewxDIFtoiuym0PDT
            PoS2+RwDVaY9HoeWpK+1RGXnrRVuMgh
            bA67RFd+RtOe0w3wMtgKhFtMNS5KlYN
            m3wQyFoASVtoQ2yiiAvXtrg1FXQgqib
            RRvci7zMog2ehhZUf9pgOvIQc5jyPvV
            ACyrqK8pLi8albqa8tIrQ8lElnfKa4F
            JjKO9eaPl6kPJew6V+obh/QgvB+xS3H
            ZdIprhdRaGFoMReiquFi/WhuBbQQnIn
            xfXBxeZT2mJoIVpOafNxsRQKy0mGFqI
            6uRSWgovUoLSJ0EL2FqXVwIU6U1h6aW
            ghK59BYZ1xoakU1heaAYMpbCoutJWyd
            sZBMyBxD2VtxQVK+imrHTRDHqAsf0mc
            rw1lbYBmjGcTZbXB+UZS1oPQDHqUskb
            ifCspan8sNIMSUilqJc4Td4qiBkMz7A
            WKOhWHcxpR1KnS0Awrl0lRjXBOX4qaC
            s2EtymqL875F0XVhmbCNRT1L5yTSkmf
            QjNlGSWl4n9qUFQbaKbcQVE1cFZbSjo
            cC82U2MOU1BZnDaSkd6CZ9A4lDcRZMy
            ipNTSTWlPSDJy1noLS46CZFJdOQevxX
            57jFDQDmmkzKOi4B2dUoaS7oJl2FyVV
            wRmtKOhYAjTTEo5RUCuc8SwFzYZmwWw
            KehZnvElBXmgWeCnoTZyxmoIqQ7OgMg
            WtxhlHKOd3aJb8TjlH8IcKFPQ+NEvep
            6AKOK0pBfWGZklvCmqK03pQUENoljSk
            oB44bSLlnIqFZknsKcqZiNO+oJyV0Cx
            aSTlf4LTdlDMKmkWjKGc3TsuinHbQLG
            pHOVn4j1IUdC00i+pQUCkAtSmoCDSLi
            lJQbQDNKecgNMvSKKc5gE6UswaaZRso
            pxOAfpTzHjTL5lFOPwBjKGcENMtepZw
            xAGZTzmPQLOtGObMBfEE5zaBZdjvlfA
            FgG+VUg2ZZMuVsA5BOOYWhWVaSctKBR
            Mrxe6BZFk9BiahGOSehKZBDOdXQmHIO
            QlMgnXIaox3l/AZNgX2U0w7dKWcrNAV
            +ppzuGEQ566Ap8B3lDMJLlPMVNAVWUs
            5LeJVylkBT4GPKeRXjKWceNAXmUc54T
            KWcedAUmEc5UzGDchZBU2AR5czAXMpZ
            Dk2B5ZQzFwspZxU0BVZRzkIso5wN0BT
            YQDnLsIJytkBTYAvlrMBaytkJTYGdlL
            MWP1LOPmgK7KOcH7Gdcg5DUyCNcrZjD
            +WchKbACcrZg1TKyYWmQC7lpOIYBcVB
            syyOgo4hm4KKQrOsKAVlI5eCykGzrBw
            F5eI4BV0DzbKrKSgDBymoBTTLbqWgVO
            ymoC7QLOtMQb9hGwUNhGbZAAraiu8pa
            Bw0y8ZR0AasoqB50CybS0Er8RkFrYJm
            2dcUtBQLKehXaJb9SkELMIeCTkGz7BQ
            FzcY0SioBzaLilPQmJlHSVdAsuoqSxm
            MMJTWHZlEzShqF4ZTUGZpFD1HS8xhES
            a9As2gkJfVHH0paDM2iRZTUA10p6Xdo
            Fv1GSY+gM0UVh2ZJUYry4j6KuhGaJY0
            p6i7cQVHdoFnyJEXdimYUNQmaJRMo6n
            pcS1FfQ7PkK4q6EiUoKh2aJWkUVQjIo
            Kg/QbPgMoo6BGArRbWGZkFLivoewCcU
            9TdoFvSjqI8ATKWopdAs+IiiJgIYSlE
            n46GZFnOMogYA6EJZTaGZ1piyHgDQjL
            JGQDNtCGU1AXAFZa2FZtpXlFUNQCJl5
            ZaAZlLhLIryx+E/UimrHTSTbqOsAzht
            A2VNgmbSa5S1FqctoKxfoJn0A2V9gNP
            GUVhVaKaU8VPWWJzWj8Ieg2ZKBwp7Fq
            d1oLDF0EyZSWH34bTGFJZTBpoJhY5TW
            COcVpnSukMz4X5Kq4TTon0UthqaCQsp
            zBeNP2yjtGrQDCuVTWHbcMZsShsEzbA
            nKW02zuhHaVuhGfYVpfXDGc0orh40gy
            r7Ka0ZzihBca9BM6g/xZXAf+2itL1R0
            Iz5gdJ24awPKO42aIZcS3Ef4KxBFLcU
            miHvUNwgnHU75V0NzYAKWRR3O84qT3l
            vQTNgBOWVx//sp7jMstBCVvgwxe3HOY
            so7wVoIetJeYtwzouUl5oALUTROynvR
            ZxzN23wGLQQ3Usb3I1zqtAGWzzQQvMN
            bVAF50mjDVpDC8kNtEEazreMNtgcDS0
            UX9MGy3C+UbRDV2ghaE87jML5vLRDSl
            Fo+YrfRTt4cb4atMUr0PL1HG1RAxfYT
            TtkVoWWj7LHaIfduNBk2uI9aPmYTFtM
            xoXuoT0aQQvqGh9tcTcuVDSHtvgmClo
            wy2iLnKK4yAraox+0IB6hPVbgYoNoj6
            x60AKqeZz2+Bsu1oA22ZoILYC472iT+
            riYJ5U2+T9oAYyhTVI8uMRM2qUNtDzd
            5qdNZuBSD9IuKeWg5aFcCu3yAC5V1k+
            7LIZ2Kc8ntIu/DPKwgbYZAe0SI2ibdc
            jLy7RPV2gX6UX7DEdebqR9fHdAu0BHP
            +1zA/ISc5T2OdEQ2nlaZtM+6THI03za
            KPVyaP/T8DhtNA95e4J2+qU0tP+qdYh
            2egx5q0JbrSsF7Q81dtNWlRHAVtpqa2
            Vo//HnVNpqMwIZSnvtqQUNLTJor78hk
            Kp+2utQQxR4HbNpL/+fENBXtFnGrSjg
            +vhps+UI7BHaLes+FGSeV2m7hxBYkZO
            0W+6QKBRYRefSdhmFEcQs2u/Tsiig6u
            +g/aYhmBZ0wP6bUCB1z6QDmiKYqH10g
            G+QBwVOsbl0wm4PghpFR3xSBgXMn3fS
            EcMRXG06Y19LFCTRfbPojCuRj/V0yPs
            VUGA0+oEOWY38PE2nHO0ehQKh5BQ/nd
            IV+SmdTcesrY/I5+lykI7JLI58fUjn+
            MYWQYSrvYIOmoP83UMn7X0sBhGs3Lgc
            Oqk18heXRkdtv9+DCFVi5Ak66t8xCMF
            EOmzjnYhESYPT6bDRCEVDOu7bZog0Cc
            +k0nF1EJKNdN7nzRFJCvX4nc5bg9B0p
            Gk5mVTlh06xiBDlX06jG7RDaGJ20bDt
            o1v/tVbFwvBUavrU60t2+KnA3v7FEQG
            ufjuLrrA9CiHqQYMm18SFqgzcTAUyxl
            ZFmGv+Md3icYQqMZWG/B15qPvqXlrn+
            /i+eIStis9to2sciEfIhtCIw8hbVNPZ
            flqXNqEBwlHcvYt9dJHnELqSGTTgFAK
            6bh1V+PGZMggz9cYdoqscLQYDxtCIax
            FQ1KMpVMG3ol8thIvYpq/vpNuMghGVs
            mnAmigEVuz1HKqxffTNMXC9Eh3fTaf7
            ZFWAIdNoRG8Ec9UyqnL4g343FoJrVWj
            7yoocutKbMOYqPw04XhVB3b2L6uR8N6
            lzTQ9cJuH6PnN207Vya8KgD2nEJwiu6
            FyqdeSTYa1KwiWueHDCumy62nwY1YiG
            TI5CcL2zqdz26d0blYaToqveNnTJIbr
            fX2HYChoyNw7BNf6dIo5umDPi0ZsqeW
            Cr+Fqte41b8nM2w8OXMK41jVmWhODKr
            KSgU1s+HNOt5eUxEJZUt91zUz7fncuw
            0grGeX6kMWtLI7hCyyguZ20xCGpygOF
            oI8x4kAbtaYLgEhZR2slGEPWEn2HoAZ
            gR8xsNyh1ZCEHFzqMsXxsIe9zPsPNbD
            Ex5kobtezgKwUS/T1GPQNyjfoabJ2FO
            9CYat/EGBBO/ioIGwQa9GGY2RcOkFjQ
            hpy+CKbOLYibAFu8xvLSAaYtpxrwiCK
            L2UQqZGwVbJP3EcLIY5iXn0Ixt1RDEb
            T6K2F8UNql9nOEjJxkWjKcpe2ogiKEU
            8QBs8yDDx3hYUeoITdlXC4HFfE8BX8F
            GixkujpSCJc/QnH9fjcDqZFO5nGtgoy
            uyGCaegTWxv9Cc/ZchsBeo3FjYaiTDw
            y+xsKgtTfquEAKK3UjF/l0Utiq8l2Gh
            LSz7nCbN9yCgBj6q1Qk268hw8Dmsq5t
            Lk0YgsNep1Newm2cb3S+3LhR4i2a1Q0
            BJe6jS3bBdd7rfW1ChfAZNOlQBAd1Jh
            Q7GwnZJ6XS7jPJQYhDN+hiBzac64+CA
            MXS7QVAjYTfN6oaALjtGZerDAdVz6W6
            7E6DI/TTrRE0E1J2qbIIjFtPd7ocqnm
            9o1toYBDSHivSFIx6mq33jgTK1M2nWM
            ARUeDOV8JWHI8rm0sUya0Oh/jTL91cE
            VOMIVVgMh6ymi/WHSlGradb2wgiotZ8
            KtIdDBtC9VkdBqStP0qxRCGworctNgk
            Nq07VOXgnFetGsk5chIM9MWrYFjvmVb
            tULqnm+pFlTEFj0TFo1HY6ZTpf60gPl
            qmXQpJwrEVj0TFr0NBzTk+6UUQ0CutK
            sOQgieiataQzHNKI7dYWIT2mSvwGCiJ
            5JK3yF4JjEHLrRp5BROZ0mfYpgokf4a
            d4mOOgHulB6ZQh5mGY1RVCtD9O0d+Cg
            N+lCD0PMIpq0EsFVXUezesBB3eg+iyC
            nQhpNaoDg4ifRpOvgoNZ0nbQKENSRJk
            1Hfm7fRjPWJcJB19J1OkLUBzQnqzzyE
            9v7CA069kY9OKok3eYDyCqTSnOGIX+l
            J/lowPrHk+C0E3SX1DIQdg/NSYlHCK5
            6I4Oh2Tq2AVzgZ7rLPRA3luZ0RkiKdt
            /C/KTM6nIZ3OEzuspYyItZQVO+R6hum
            rjZzwCOfTenX10PXGMa3WRFDGxQbh9N
            uQGhK33PP9buzeRZuRkpu76b8/LDN5S
            Hy4yji+wrB1s0yqIZ78KoItX+0rjulZ
            VKJsC1RtE9shrBJk/RjOzyiDzD6B5Pw
            TbTaMZQRJ6BdI1psE/CBpqwLwYR5xm6
            xYYE2KjKIZrQHhHnKbrEoSqw1a25NG5
            LLCJNF7pD7q2w2UCa0A+R5n66w0DYzT
            Ofxh2vjAjjpSvM98B2RbbRuHmIMF66w
            bYicEDyMRp3GyKLly5wLBmOaEfjdpZA
            RPHSBdrBIa/QuM9iEEm8dN4rcEr0Mhr
            3BiKJl45bFg3HFPuexj2NCOKl074vBg
            eV20HDfLchcnjpsB3l4KjqB2jYsVsQM
            bx01oHqcFiddBqW1RGRwktHpdeB45qc
            omH+5xAhvHTSqSZwgTt9NG5iFCKClw7
            y3QlXeJgmLCyNSOClgx6GS/SnCSl3Iw
            J46Zz+cI3XaMbMEgh7XjrmNbiHZxrN2
            N8a4c5Lp0zzwEViFtKUxfUQ3rx0yMIY
            uEriSprin1ML4cxLZ6xMhMsU/5Hm+KZ
            djvDlpSN+LA7XqfArTfIvf7AQwpSXTv
            i1Alyoxn6adnRKI4QlLx2wrwZcqfpOW
            rB/Ts+6UQg3XtpvZzW4VIXNtCZ9yctd
            biiHUJW+5empjeEoL223qQJcq+QaKnD
            su/eHd7m+LAJLSm7x2OhPD/A/7oGjvL
            TbtyXhYknLqcyxnd998eH08cP7P+lt1
            bRlm3s6dHqka89nh7yx+McjPKcdHOWl
            zT5LgqvFL6C92sNRXtprfjxcLmY6bXU
            fHOWlrd6Jhut5xtNOXjjKSzu97kE4eI
            k26ghHeWmjoQgTfWifB+AoL23j74mw8
            YiPdukER3lpl5xOCCP3ZtEmD8FRXtok
            8y6ElZYnaI8ucJSX9si4BWGm8RHa4hE
            4yktbHPoLws5V22mHR+EoL+2w5QqEoW
            ILaYPH4SgvbfBBEsKSZ5if4p6Eo7wUl
            zvIg3B151FK6wpHeSntSCuEsZo/UVg3
            OMpLYZtqIKwV+RdldYejvJQ1NwlhzjM
            4l5J6wlFeSsodgAhw+xEK6gVHeSnocE
            tEhBqbKKc3HOWlnB+rI0IUnkMxfeAoL
            8W8XxiR47lcCukLR3kpxNcPEeXWNMro
            B0d5KSPtVkSYqiso4jk4yksRX1VFxIn
            qfZICBsBRXgo42cuDSHTlaqr3NzjKS/
            VWXYEIFd0/k6oNhqO8VO1U3yhErqvWU
            bEhcJSXiq2phYgWMzibSj0PR3mpVOaA
            aES6Oj9QpWFwlJcqra+NAiD2xRyq8xI
            c5aU62UNiUDA02ExlXoajvFTm+zooMO
            Jf8VGRkXCUl4rkDItFQXLdNqrxdzjKS
            zU21UcBk/j8CarwGhzlpQpHB8Sh4Kn4
            Ti6tGwNHeWmd742yKJjqfUHLxsJRXlq
            29GoUXHf9TIvGw1FeWrS1FQq02F5ptG
            QiHOWlJQe7xaCgKzEmmxZMgqO8tCDr1
            WLQgBrzad5kOMpL8+ZVh3ZGk/U0ayoc
            5aVZ626A9j+eh/bSnLfhKC/N+b2TB9r
            5Cg3NoBnT4CgvzcgYkgjtYiUGpdC46X
            CUl8alDCoBLS8JT+2gUTPhKC+N2tE1A
            Vog0fdtoDGz4agONGZ9+yhoQTVfRiMm
            w1GtaMTSZtDyV/99H0P2AhxVlyHzvVs
            XWmgun3SKIXocjirDEJ2cUA1a6MoOP8
            yQ1ISzfmYo0oaVhmZMUp/fmb+f4LDRz
            N/uXoWhGRd73xIf8zEEDmvIfOQsbBcD
            zaQK/bYwmH2F4bQFDGbTs+WgWfLnCWk
            M6CE47qpsBnJoXH1o1sW1W5jDPI2DC3
            RhnnI+uicOmiLl+vzIS82JghsM46U2P
            lMWmlL1/3GQF8jsFwV36JTOCxwcWw+a
            erFtF2TzrIx5V8E1/jQznWdlL2gbC01
            ImTu7jZz50YwJL90eD1eJbfHi+BkfzR
            zZ7c4y0DRN0zRN0zRNc7H/B5My2wke0
            lCHAAAAAElFTkSuQmCC}
        return gitlogo
    }
}